language: php
php:
  - 5.4
  - 5.5

cache:
  directories:
  - vendor/

branches:
    only:
        - master

before_install:
    - mysql -uroot -h localhost -e "USE mysql; UPDATE user SET password=PASSWORD('topsecret') WHERE user='root'; FLUSH PRIVILEGES;"

install:
    - rm -rf vendor/magento
    - composer install --prefer-source --no-interaction
    - sh install.sh

script:
    - vendor/bin/phpunit
    - rm -rf vendor/magento
    - rm -rf vendor/autoload.php
    - rm -rf vendor/composer/autoload_classmap.php

notifications:
  flowdock:
    secure: FLOWDOCK_KEY